name: portfolio-construction-riskfolio
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - pip==24.3.1
  - ipykernel==6.29.5
  - nb_conda_kernels==2.5.1
  - altair-all==5.4.1
  - vega_datasets==0.9.0
  - scipy==1.14.1
  - matplotlib==3.9.2
  - scikit-learn==1.5.2
  - pandas==2.2.2
  - numpy==2.2.1
  - quarto==1.5.57
  - make=4.4.1
  - pytest=8.3.4
  - click=8.1.7
  - requests=2.31.0
  - responses=0.24.1
  - yfinance==0.2.51




